### ISSUE TITLE
Issue with nested active states

### ISSUE THREAD

**Issue by liorocks** [zgabievi/bem#4]
``` sass
@include c('menu') {
    @include is('open') {
      @include e('item') {
       .....
      }
    }
}
```

Should render the following css:

``` css
.c-menu.is-open .c-menu__item { .... }
```

**Comment by liorocks** [comment]
Same story with `@has` and etc.

**Comment by zgabievi** [comment]
Fixed this issue, will be in next minor version. You can check this: 88c775ec5b4ab6a8629bf48b6112ce46f3f59708

**Comment by liorocks** [comment]
Nice, add this to the docs as well as the #5

**Comment by zgabievi** [comment]
They are added. But sassdoc has some issue with aliases, they will be fixed soon I think ;)

**Comment by Landish** [comment]
It has issue with `@hover` : (
