### ISSUE TITLE
Issues with nested elements

### ISSUE THREAD

**Issue by liorocks** [zgabievi/bem#5]
``` sass
@include c('menu') {
  @include e('button') {
    @include e('item') {
      ...
    }
  }
}
```

Should return the following css:

``` css
.c-menu .c-menu__button__item { ... }
```

**Comment by zgabievi** [comment]
I think it's better to leave elements simple. Nesting classrs is not reusable. As much as simple classes. Thats why it is outputing:

```
.c-menu .c-menu__button .c-menu__item {
    ...
}
```

**Comment by zgabievi** [comment]
Added second optional parameter to `element` mixin (or you can use `e`). This parameter is boolean type, It should be true, if element is nested with another element. By default it's false. [b03bb8e945d649d9f5f3c5004a2c610829980f21]

**Comment by zgabievi** [comment]
Or you can simply use `ee` mixin
