### ISSUE TITLE
mistake in docs v2.5.3 - mixin At - section Usage

### ISSUE THREAD

**Issue by MartinN3** [zgabievi/bem#9]
Hello i found small mistake in docs that confused me a bit yersterday. You got `@include m` instead of `@include at`

Output should be 
`.list--inline .list__item {
    color: black;
}`

Usage is now
`@include b('list') {
    @include e('item') {
        @include m('inline') {
            color: black;
        }
    }
}`

should be 
`@include b('list') {
    @include e('item') {
        @include at('inline') {
            color: black;
        }
    }
}`

**Comment by zgabievi** [comment]
Thank you @MartinN3. You are right. I will fix it.

**Comment by zgabievi** [comment]
Fixed in v2.6.0
